version: 0.0.1
metadata:
  code: SUPER-TEST-
  name: "Super test "
  description: this is the new restqa project
environments:
  - name: local
    default: true
    plugins:
      - name: "@restqa/restqapi"
        config:
          url: http://localhost:8000
    outputs:
      - type: html
        enabled: true
      - type: file
        enabled: true
        config:
          path: restqa-result.json
